Blac 44 check and apply for open vacancy
BlackFoxSprint/BlackFox pull request #10
Opened 2023-06-20 17:29 UTC by kimkaminska

2023-06-20 18:15 UTC, VityaPodill approved these changes

2023-06-21 09:50 UTC, Bogdan27nazaruk approved these changes

2023-06-21 09:50 UTC, Bogdan27nazaruk approved these changes

2023-06-21 09:56 UTC, Bogdan27nazaruk approved these changes

2023-06-21 10:00 UTC, NataLitovets approved these changes

2023-06-21 10:00 UTC, AndriiMyronenko91 requested changes

2023-06-21 10:00 UTC, AndriiMyronenko91 commented on src/test/java/elements/ApplyForOpenJobElements.java
> +    private static final String ENTER_USERS_EMAIL = "//input[@data-automation-id='email']";
please create a method dataAutomationId() the same as dataTestId() and use it here

2023-06-21 10:00 UTC, AndriiMyronenko91 commented on src/test/java/elements/ApplyForOpenJobElements.java
> +    private static final String ENTER_USERS_PASSWORD = "//input[@data-automation-id='password']";
ditto

2023-06-21 10:00 UTC, AndriiMyronenko91 commented on src/test/java/elements/CareersElements.java
> +    private static final String LOCATIONS_FILTER = "//div[@class= 'jobfinder-filter-list-container job-corporate active']//span[text()= 'Locations']";
there are two unnecessary spaces it this locator

2023-06-21 10:00 UTC, AndriiMyronenko91 commented on src/test/java/elements/CareersElements.java
> +    }
your style of getters are different from other developers in this framework. Please choose one style

2023-06-21 10:00 UTC, AndriiMyronenko91 commented on src/test/java/elements/HomeElements.java
>      public static final String SELECT_LOCATION_CLOSE_BTN = "//button[@data-test-id='close-btn']";
use dataTestId() method please

2023-06-21 10:00 UTC, AndriiMyronenko91 commented on src/test/java/elements/HomeElements.java
>      public static final String COOKIE_CLOSE_BTN = "//button[@data-test-id='cookie-banner-close-btn']";
ditto

2023-06-21 10:00 UTC, AndriiMyronenko91 commented on src/test/java/elements/HomeElements.java
>      public static final String ACCOUNT_ICON_BUTTON = "//button[@data-test-id='account-button']";
why are these variables public?

2023-06-21 10:00 UTC, AndriiMyronenko91 commented on src/test/java/elements/HomeElements.java
>      public static final String SEARCH_FIELD = "//button[@data-test-id='search-icon-nav']";
public?

2023-06-21 10:00 UTC, AndriiMyronenko91 commented on src/test/java/elements/HomeElements.java
> +
remove empty line

2023-06-21 10:00 UTC, AndriiMyronenko91 commented on src/test/java/elements/HomeElements.java
> +
remove empty line

2023-06-21 10:00 UTC, AndriiMyronenko91 commented on src/test/java/elements/HomeElements.java
> +
remove empty line

2023-06-21 10:00 UTC, AndriiMyronenko91 commented on src/test/java/elements/HomeElements.java
>      public static final String HATS_ACCESSORIES_MEN_CATEGORY = "//a[@data-link-name='Hats']";
public?

2023-06-21 10:00 UTC, AndriiMyronenko91 commented on src/test/java/pages/CareersPage.java
> +        sleep(3000);
why do you need sleep here?

2023-06-21 10:00 UTC, AndriiMyronenko91 commented on src/test/java/pages/CareersPage.java
> +        sleep(3000);
sleep?

2023-06-21 10:00 UTC, AndriiMyronenko91 commented on src/test/java/pages/CareersPage.java
> +        sleep(2000);
sleep?

2023-06-21 10:00 UTC, AndriiMyronenko91 commented on src/test/java/pages/CareersPage.java
> +        sleep(3000);
sleep?

2023-06-21 10:00 UTC, AndriiMyronenko91 commented on src/test/java/tests/CheckAndApplyForOpenVacancy.java
> +                //test fail at this step from time to time
stabilize it and remove comment please

2023-06-21 10:00 UTC, AndriiMyronenko91 commented on src/test/java/tests/CheckAndApplyForOpenVacancy.java
> +                //test fail at this step from time to time
ditto

2023-06-21 10:00 UTC, AndriiMyronenko91 commented on src/test/java/tests/CheckAndApplyForOpenVacancy.java
> +                //test fail at this step from time to time
ditto

2023-06-21 10:00 UTC, AndriiMyronenko91 commented on src/test/java/tests/CheckAndApplyForOpenVacancy.java
> +                //test fail at this step from time to time
ditto

2023-06-21 10:38 UTC, kimkaminska commented on src/test/java/elements/ApplyForOpenJobElements.java
> +    private static final String ENTER_USERS_EMAIL = "//input[@data-automation-id='email']";
Ok, thanks

2023-06-21 19:37 UTC, kimkaminska commented on src/test/java/elements/ApplyForOpenJobElements.java
> +    private static final String ENTER_USERS_EMAIL = "//input[@data-automation-id='email']";
done

2023-06-21 19:38 UTC, kimkaminska commented on src/test/java/elements/ApplyForOpenJobElements.java
> +    private static final String ENTER_USERS_PASSWORD = "//input[@data-automation-id='password']";
Thanks. Done.

2023-06-21 19:50 UTC, kimkaminska commented on src/test/java/elements/CareersElements.java
> +    private static final String LOCATIONS_FILTER = "//div[@class= 'jobfinder-filter-list-container job-corporate active']//span[text()= 'Locations']";
Thanks, corrected

2023-06-21 19:52 UTC, kimkaminska commented on src/test/java/elements/CareersElements.java
> +    }
Thanks. We've already discussed with You this comment.

2023-06-21 20:01 UTC, kimkaminska commented on src/test/java/tests/CheckAndApplyForOpenVacancy.java
> +                //test fail at this step from time to time
Ok, thanks

2023-06-21 20:01 UTC, kimkaminska commented on src/test/java/tests/CheckAndApplyForOpenVacancy.java
> +                //test fail at this step from time to time
Ok, thanks

2023-06-21 20:01 UTC, kimkaminska commented on src/test/java/tests/CheckAndApplyForOpenVacancy.java
> +                //test fail at this step from time to time
Ok, thanks

2023-06-21 20:02 UTC, kimkaminska commented on src/test/java/tests/CheckAndApplyForOpenVacancy.java
> +                //test fail at this step from time to time
Ok, thanks

2023-06-22 08:48 UTC, kimkaminska commented on src/test/java/elements/HomeElements.java
>      public static final String SELECT_LOCATION_CLOSE_BTN = "//button[@data-test-id='close-btn']";
Thanks, Ok

2023-06-22 08:50 UTC, kimkaminska commented on src/test/java/pages/CareersPage.java
> +        sleep(3000);
Test failed without sleep. I'll try to avoid sleep.

2023-06-22 13:13 UTC, merged